
// Objective-C API for talking to the following Go packages
//
//	thuannek69.com/detectface
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FaceDetection_FRAMEWORK_H__
#define __FaceDetection_FRAMEWORK_H__

#include "FaceDetection.objc.h"
#include "Universe.objc.h"

#endif
