// Objective-C API for talking to thuannek69.com/detectface Go package.
//   gobind -lang=objc thuannek69.com/detectface
//
// File is generated by gobind. Do not edit.

#ifndef __FaceDetection_H__
#define __FaceDetection_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FaceDetectionFaceDetect;
@class FaceDetectionFaceLandMark;

@interface FaceDetectionFaceDetect : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long cols;
@property (nonatomic) long rows;
@property (nonatomic) long minSize;
@property (nonatomic) long maxSize;
@property (nonatomic) double shiftFactor;
@property (nonatomic) double scaleFactor;
@property (nonatomic) double angle;
@property (nonatomic) double ioThreshold;
@property (nonatomic) NSString* _Nonnull faces;
@property (nonatomic) long numFace;
- (void)getFacesDetect:(NSData* _Nullable)pixels cols:(long)cols rows:(long)rows;
@end

@interface FaceDetectionFaceLandMark : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long cols;
@property (nonatomic) long rows;
@property (nonatomic) long minSize;
@property (nonatomic) long maxSize;
@property (nonatomic) double shiftFactor;
@property (nonatomic) double scaleFactor;
@property (nonatomic) double angle;
@property (nonatomic) double ioThreshold;
@property (nonatomic) NSString* _Nonnull faces;
@property (nonatomic) long numFace;
@property (nonatomic) NSString* _Nonnull holesFace;
- (void)getFaceLandMark:(NSData* _Nullable)pixels cols:(long)cols rows:(long)rows;
@end

FOUNDATION_EXPORT FaceDetectionFaceDetect* _Nullable FaceDetectionInitFaceDetect(NSData* _Nullable cas);

FOUNDATION_EXPORT FaceDetectionFaceLandMark* _Nullable FaceDetectionInitFaceLandMark(NSData* _Nullable facecascade, NSData* _Nullable puplocCascade, NSData* _Nullable lp38, NSData* _Nullable lp42, NSData* _Nullable lp44, NSData* _Nullable lp46, NSData* _Nullable lp81, NSData* _Nullable lp82, NSData* _Nullable lp84, NSData* _Nullable lp93, NSData* _Nullable lp312);

#endif
